language: java
jdk:
  - oraclejdk7
script: "mvn clean deploy --settings .utility/settings.xml"
notifications:
  email: false
env:
  global:
    secure: "AlrQfjGkeNP4ndYrGYJoNvtTrTKawSKzzQz/NNdq2uBxMrBtNOuGfLCV1d9Vi4suFTQtNzVzy63VhvvjMVegv6vrCQs21htn4kkNEjnAKdqtlIlUvZqke6R2zMnXdwpgWqdD/Sjx/6h8dFYsLQ3w0xLh8BAqqoD/UUHkZievEj4="
    secure: "BszBmU9H71R7e2ln5b13j3+oABm2qMUjubhZ1/SMI9UVVJC0hZMKtQRYy6YfG0mMyQkQ4qVOB445cfE34WczDh3DNEYiqCoWS0uPcbuO6K8g4wgAzL+KBWJeS7NmNTdSreHxFERjSGgwL0z0FKrUJsPU4PqsRoRbJxijc3zdO5A="