language: java
jdk:
  - oraclejdk8
script: "mvn clean deploy --settings .utility/settings.xml"

after_success:
  - chmod 777 ".utility/jd.sh"
  - sh .utility/jd.sh
  
notifications:
  email: false
  
env:
  global:
    - secure: "vxAyGB4XL5XkO2rCYHEo1aH3PzCk/fYWJU7oc0nu6TBXo4+N/JlJ+YDwZ30PwAmnb5S8Lqq/PFvYbCspeO107huNoNu99kR6aKfHpLB4kg8NFCbzUQi+73kSMKF3NC6HTmY+BLaFmkr4wPqN6o9lEzyvSHNQuujW73nQ1bD2zucqMsEv7IvOWp71lsGXYqYWbVM5l28XEa0gAdmcJ8Q0CvvZseDFuLpBGyha5yEPwRt9boXwpXUd8YI0v4SuonSbMHxXWyX8Z4G6QuIdH419pALO436iZuW4hrgTyUcu12iJUu8Ww7nh9qBBFENn5aTG6BjnTKqxIDYADzqSdtD7Ew=="
