language: java
jdk:
  - oraclejdk8
script: "mvn clean deploy --settings .utility/settings.xml"

after_success:
  - chmod 777 ".utility/jd.sh"
  - sh .utility/jd.sh
  
notifications:
  email: false
  
env:
  global:
    - secure: "nMs5eEZMHcnvEO9wmuAK+67VdRKdhPqPGCG8JdzQ6P6LnEleYfXDLAVNYX95VwIoEhxaiXIvSJQgzbfueSP85Ndv1lbX6M4KGSdJw1h1y8S5bh5LSvV/K/7c2TKj9UeNLUMcc5lg8/y4DiaDggALuZHscCGvBtiCaoA/Bh3JSGfuXM9sXOmgnWjgEPFi0o8pHdmIQKjNncXmdqZL4qGgEeNfF4VGt2t7La3PnGDrhioioBdL2XAl46vha3kWSvBQwxM6ovvhLk7AMCXcSR05bt62xfrlYvgLmK8WhRnP9Q1kk00nTKPL35OHOqRBQSaW0lzKbxMV+Qj/AUzMTEBdmQ=="
