main: com.gmail.woodyc40.commons.Main
name: BukkitCommons
version: 1.0
description: Common library for all utilities
author: xTrollxDudex or AgentTroll

commands:
  check:
    description: Checks location walker
    usage: /<command>